import { Ban, Banknote, Pencil, Plus, Search } from "lucide-react";
import { useState } from "react";
import { Badge } from "../components/Badge";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { DataTable } from "../components/DataTable";
import { EmptyState } from "../components/EmptyState";
import { Modal } from "../components/Modal";
import { useToast } from "../components/ToastProvider";
import { useAsync } from "../hooks/useAsync";
import { customerService } from "../services/management";
import type { Customer, CustomerPayment } from "../types";
import { formatCurrency, formatDateTime } from "../utils/format";

const emptyForm={name:"",phone:"",whatsapp:"",cpf:"",address:"",notes:"",credit_limit:"",credit_blocked:false,active:true};

export function CustomersPage(){
  const toast=useToast(); const [search,setSearch]=useState(""); const {data,loading,setData}=useAsync(()=>customerService.list(),[]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Customer|null>(null); const [form,setForm]=useState(emptyForm); const [selected,setSelected]=useState<Customer|null>(null); const [paymentOpen,setPaymentOpen]=useState(false); const [payment,setPayment]=useState({amount:0,method:"DINHEIRO",notes:""}); const [receipt,setReceipt]=useState<CustomerPayment|null>(null);
  async function refresh(){setData(await customerService.list(search));}
  function edit(customer?:Customer){setEditing(customer??null);setForm(customer?{name:customer.name,phone:customer.phone??"",whatsapp:customer.whatsapp??"",cpf:customer.cpf??"",address:customer.address??"",notes:customer.notes??"",credit_limit:customer.credit_limit?.toString()??"",credit_blocked:customer.credit_blocked,active:customer.active}:emptyForm);setOpen(true);}
  async function save(event:React.FormEvent){event.preventDefault();const payload={...form,credit_limit:form.credit_limit===""?null:Number(form.credit_limit)};try{if(editing)await customerService.update(editing.id,payload);else await customerService.create(payload);toast.push(editing?"Cliente atualizado.":"Cliente cadastrado.");setOpen(false);await refresh();}catch(error){toast.push(error instanceof Error?error.message:"Não foi possível salvar.","error");}}
  async function show(id:number){setSelected(await customerService.get(id));}
  async function pay(){if(!selected)return;try{const result=await customerService.pay(selected.id,payment);setReceipt(result);setPaymentOpen(false);setSelected(await customerService.get(selected.id));await refresh();toast.push("Pagamento registrado.");}catch(error){toast.push(error instanceof Error?error.message:"Não foi possível registrar.","error");}}
  async function toggleBlock(){if(!selected)return;const updated=await customerService.update(selected.id,{name:selected.name,phone:selected.phone,whatsapp:selected.whatsapp,cpf:selected.cpf,address:selected.address,notes:selected.notes,credit_limit:selected.credit_limit,credit_blocked:!selected.credit_blocked,active:selected.active});setSelected(await customerService.get(updated.id));await refresh();toast.push(updated.credit_blocked?"Fiado bloqueado.":"Fiado liberado.");}
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="page-title">Clientes e fiado</h1><p className="page-subtitle">Cadastro rápido, limites, dívidas e pagamentos.</p></div><Button onClick={()=>edit()}><Plus size={16} className="mr-2"/>Novo cliente</Button></div><Card><div className="flex gap-2"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="w-full rounded-xl border-stroke bg-white pl-10" placeholder="Nome, telefone ou CPF" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void refresh()}/></div><Button variant="secondary" onClick={()=>void refresh()}>Buscar</Button></div></Card><Card>{loading||!data?<p className="text-sm text-slate-500">Carregando clientes...</p>:!data.length?<EmptyState title="Nenhum cliente" description="Cadastre um cliente para identificar compras e usar fiado."/>:<DataTable headers={["Cliente","Contato","Limite","Saldo","Atrasado","Fiado","Ações"]}>{data.map(item=><tr key={item.id} className="cursor-pointer hover:bg-brand/5" onClick={()=>void show(item.id)}><td className="px-4 py-3 font-medium">{item.name}</td><td className="px-4 py-3">{item.whatsapp||item.phone||"-"}</td><td className="px-4 py-3">{item.credit_limit==null?"Sem limite":formatCurrency(item.credit_limit)}</td><td className="px-4 py-3 font-medium">{formatCurrency(item.balance)}</td><td className="px-4 py-3 text-rose-600">{formatCurrency(item.overdue_balance)}</td><td className="px-4 py-3"><Badge label={item.credit_blocked?"BLOQUEADO":"LIBERADO"}/></td><td className="px-4 py-3"><Button variant="ghost" onClick={event=>{event.stopPropagation();edit(item);}}><Pencil size={15}/></Button></td></tr>)}</DataTable>}</Card>
  {open&&<Modal title={editing?"Editar cliente":"Novo cliente"} onClose={()=>setOpen(false)}><form className="grid gap-4 md:grid-cols-2" onSubmit={save}>{[["name","Nome"],["phone","Telefone"],["whatsapp","WhatsApp"],["cpf","CPF"],["address","Endereço"],["credit_limit","Limite de crédito"]].map(([key,label])=><label key={key} className="text-sm">{label}<input required={key==="name"} type={key==="credit_limit"?"number":"text"} min={key==="credit_limit"?0:undefined} step={key==="credit_limit"?"0.01":undefined} className="mt-1 w-full rounded-xl border-stroke bg-white" value={String(form[key as keyof typeof form])} onChange={e=>setForm(current=>({...current,[key]:e.target.value}))}/></label>)}<label className="text-sm md:col-span-2">Observações<textarea className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><Button className="md:col-span-2">Salvar cliente</Button></form></Modal>}
  {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)}><div className="space-y-5"><div className="grid gap-3 md:grid-cols-3"><Card className="bg-brand/4"><p className="text-xs text-slate-500">Saldo em aberto</p><p className="mt-1 text-xl font-semibold">{formatCurrency(selected.balance)}</p></Card><Card className="bg-brand/4"><p className="text-xs text-slate-500">Total comprado</p><p className="mt-1 text-xl font-semibold">{formatCurrency(selected.total_purchased)}</p></Card><Card className="bg-brand/4"><p className="text-xs text-slate-500">Ticket médio</p><p className="mt-1 text-xl font-semibold">{formatCurrency(selected.ticket_average)}</p></Card></div><div className="flex gap-2"><Button disabled={selected.balance<=0} onClick={()=>{setPayment({amount:selected.balance,method:"DINHEIRO",notes:""});setPaymentOpen(true);}}><Banknote size={15} className="mr-1"/>Receber</Button><Button variant="secondary" onClick={()=>void toggleBlock()}><Ban size={15} className="mr-1"/>{selected.credit_blocked?"Desbloquear fiado":"Bloquear fiado"}</Button></div><div><h3 className="mb-2 font-semibold">Dívidas</h3>{!selected.debts.length?<p className="text-sm text-slate-500">Nenhuma dívida registrada.</p>:selected.debts.map(debt=><div key={debt.id} className="flex justify-between border-b border-stroke py-2 text-sm"><span>{debt.sale_number} · {debt.is_overdue?`Vencido · ${debt.days_open} dias`:`Em aberto há ${debt.days_open} dias`}</span><span>{formatCurrency(debt.balance)} · <Badge label={debt.status}/></span></div>)}</div><div><h3 className="mb-2 font-semibold">Compras</h3>{!selected.sales.length?<p className="text-sm text-slate-500">Nenhuma compra identificada.</p>:selected.sales.map(sale=><div key={sale.id} className="flex justify-between border-b border-stroke py-2 text-sm"><span>{sale.number} · {formatDateTime(sale.created_at)} · {sale.payment_method}</span><span>{formatCurrency(sale.total)}</span></div>)}</div><div><h3 className="mb-2 font-semibold">Pagamentos</h3>{selected.payments.map(item=><div key={item.id} className="flex justify-between border-b border-stroke py-2 text-sm"><span>{formatDateTime(item.created_at)} · {item.method}</span><span>{formatCurrency(item.amount)} → saldo {formatCurrency(item.balance_after)}</span></div>)}</div></div></Modal>}
  {paymentOpen&&selected&&<Modal title="Receber pagamento" onClose={()=>setPaymentOpen(false)}><div className="space-y-4"><p className="text-sm text-slate-500">Saldo atual: {formatCurrency(selected.balance)}</p><label className="block text-sm">Valor<input type="number" min="0.01" max={selected.balance} step="0.01" className="mt-1 w-full rounded-xl border-stroke bg-white" value={payment.amount} onChange={e=>setPayment({...payment,amount:Number(e.target.value)})}/></label><label className="block text-sm">Forma<select className="mt-1 w-full rounded-xl border-stroke bg-white" value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}>{["DINHEIRO","PIX","DEBITO","CREDITO"].map(item=><option key={item}>{item}</option>)}</select></label><label className="block text-sm">Observação<input className="mt-1 w-full rounded-xl border-stroke bg-white" value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/></label><Button className="w-full" onClick={()=>void pay()}>Confirmar recebimento</Button></div></Modal>}
  {receipt&&<Modal title="Comprovante de recebimento" onClose={()=>setReceipt(null)}><div className="space-y-3 text-center"><p className="text-xl font-semibold">Vendi</p><p>Recebimento de cliente</p><p className="text-3xl font-semibold">{formatCurrency(receipt.amount)}</p><p>Saldo anterior: {formatCurrency(receipt.balance_before)}</p><p>Saldo atual: {formatCurrency(receipt.balance_after)}</p><p>{formatDateTime(receipt.created_at)}</p><Button className="w-full print:hidden" onClick={()=>window.print()}>Imprimir comprovante</Button></div></Modal>}</div>;
}
