import { ClipboardCheck, Plus } from "lucide-react";
import { useState } from "react";
import { Badge } from "../components/Badge";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { DataTable } from "../components/DataTable";
import { EmptyState } from "../components/EmptyState";
import { Modal } from "../components/Modal";
import { useToast } from "../components/ToastProvider";
import { useAsync } from "../hooks/useAsync";
import { catalogService } from "../services/catalog";
import { managementInventoryService } from "../services/management";
import type { InventoryCount } from "../types";
import { formatDateTime } from "../utils/format";

export function InventoryCountsPage(){
  const toast=useToast(); const {data,loading,setData}=useAsync(()=>managementInventoryService.counts(),[]); const {data:categories}=useAsync(()=>catalogService.listCategories(),[]); const [open,setOpen]=useState(false); const [categoryId,setCategoryId]=useState(0); const [notes,setNotes]=useState(""); const [counting,setCounting]=useState<InventoryCount|null>(null); const [values,setValues]=useState<Record<number,number>>({});
  async function refresh(){setData(await managementInventoryService.counts());}
  async function create(){try{const result=await managementInventoryService.createCount({category_id:categoryId||null,notes});toast.push("Inventário iniciado.");setOpen(false);setCounting(result);setValues(Object.fromEntries(result.items.map(item=>[item.product_id,item.system_quantity])));await refresh();}catch(error){toast.push(error instanceof Error?error.message:"Não foi possível iniciar.","error");}}
  function openCount(item:InventoryCount){setCounting(item);setValues(Object.fromEntries(item.items.map(entry=>[entry.product_id,entry.counted_quantity??entry.system_quantity])));}
  async function complete(){if(!counting)return;try{await managementInventoryService.completeCount(counting.id,counting.items.map(item=>({product_id:item.product_id,counted_quantity:values[item.product_id]})));toast.push("Inventário concluído e estoque ajustado.");setCounting(null);await refresh();}catch(error){toast.push(error instanceof Error?error.message:"Não foi possível concluir.","error");}}
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="page-title">Inventários</h1><p className="page-subtitle">Compare a contagem física e ajuste o estoque com rastreabilidade.</p></div><Button onClick={()=>setOpen(true)}><Plus size={16} className="mr-2"/>Novo inventário</Button></div><Card>{loading||!data?<p className="text-sm text-slate-500">Carregando inventários...</p>:!data.length?<EmptyState title="Nenhum inventário" description="Inicie uma contagem total ou por categoria."/>:<DataTable headers={["Número","Data","Responsável","Categoria","Itens","Diferenças","Status","Ações"]}>{data.map(item=><tr key={item.id}><td className="px-4 py-3 font-medium">{item.number}</td><td className="px-4 py-3">{formatDateTime(item.created_at)}</td><td className="px-4 py-3">{item.responsible_name}</td><td className="px-4 py-3">{item.category_name||"Todos"}</td><td className="px-4 py-3">{item.items.length}</td><td className="px-4 py-3"><span className="text-emerald-600">+{item.positive_differences}</span> · <span className="text-rose-600">{item.negative_differences}</span></td><td className="px-4 py-3"><Badge label={item.status}/></td><td className="px-4 py-3">{item.status==="EM_ANDAMENTO"&&<Button variant="secondary" onClick={()=>openCount(item)}><ClipboardCheck size={15} className="mr-1"/>Contar</Button>}</td></tr>)}</DataTable>}</Card>
  {open&&<Modal title="Novo inventário" onClose={()=>setOpen(false)}><div className="space-y-4"><label className="block text-sm">Categoria<select className="mt-1 w-full rounded-xl border-stroke bg-white" value={categoryId} onChange={e=>setCategoryId(Number(e.target.value))}><option value={0}>Todos os produtos</option>{categories?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm">Observações<textarea className="mt-1 w-full rounded-xl border-stroke bg-white" value={notes} onChange={e=>setNotes(e.target.value)}/></label><Button className="w-full" onClick={()=>void create()}>Iniciar inventário</Button></div></Modal>}
  {counting&&<Modal title={`Contagem ${counting.number}`} onClose={()=>setCounting(null)}><div className="space-y-3"><p className="text-sm text-slate-500">Informe a quantidade física de todos os itens.</p>{counting.items.map(item=><div key={item.id} className="grid items-center gap-2 rounded-xl border border-stroke p-3 md:grid-cols-[2fr_1fr_1fr]"><div><p className="font-medium">{item.product_name}</p><p className="text-xs text-slate-500">Sistema: {item.system_quantity}</p></div><input aria-label={`Contagem ${item.product_name}`} type="number" min="0" step="0.001" className="rounded-xl border-stroke bg-white" value={values[item.product_id]??0} onChange={e=>setValues(current=>({...current,[item.product_id]:Number(e.target.value)}))}/><span className="text-sm">Diferença: {(values[item.product_id]??0)-item.system_quantity}</span></div>)}<div className="flex gap-2"><Button variant="secondary" className="flex-1" onClick={async()=>{await managementInventoryService.cancelCount(counting.id);setCounting(null);toast.push("Inventário cancelado.");await refresh();}}>Cancelar inventário</Button><Button className="flex-1" onClick={()=>void complete()}>Concluir e ajustar</Button></div></div></Modal>}</div>;
}
