import { AlertTriangle, Plus } from "lucide-react";
import { useState } from "react";
import { Badge } from "../components/Badge";
import { Button } from "../components/Button";
import { Card } from "../components/Card";
import { DataTable } from "../components/DataTable";
import { EmptyState } from "../components/EmptyState";
import { Modal } from "../components/Modal";
import { useToast } from "../components/ToastProvider";
import { useAsync } from "../hooks/useAsync";
import { catalogService } from "../services/catalog";
import { managementInventoryService } from "../services/management";
import type { ProductLot } from "../types";
import { formatCurrency } from "../utils/format";

export function LotsPage() {
  const toast=useToast(); const {data,loading,setData}=useAsync(()=>managementInventoryService.lots(),[]); const {data:products}=useAsync(()=>catalogService.listProducts(),[]); const {data:suppliers}=useAsync(()=>catalogService.listSuppliers(),[]);
  const [lotOpen,setLotOpen]=useState(false); const [lossLot,setLossLot]=useState<ProductLot|null>(null); const [form,setForm]=useState({product_id:0,supplier_id:0,lot_code:"",quantity:1,unit_cost:0,expiration_date:"",add_to_stock:true}); const [loss,setLoss]=useState({quantity:1,reason:"VENCIDO",notes:""});
  async function refresh(){setData(await managementInventoryService.lots());}
  async function create(event:React.FormEvent){event.preventDefault();try{await managementInventoryService.createLot({...form,supplier_id:form.supplier_id||null,expiration_date:form.expiration_date||null});toast.push("Lote registrado e estoque atualizado.");setLotOpen(false);await refresh();}catch(error){toast.push(error instanceof Error?error.message:"Não foi possível criar o lote.","error");}}
  async function createLoss(){if(!lossLot)return;try{await managementInventoryService.createLoss({product_id:lossLot.product_id,lot_id:lossLot.id,...loss});toast.push("Perda registrada e estoque baixado.");setLossLot(null);await refresh();}catch(error){toast.push(error instanceof Error?error.message:"Não foi possível registrar a perda.","error");}}
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="page-title">Lotes e validade</h1><p className="page-subtitle">Controle de vencimentos e baixas por perda.</p></div><Button onClick={()=>setLotOpen(true)}><Plus size={16} className="mr-2"/>Novo lote</Button></div><Card>{loading||!data?<p className="text-sm text-slate-500">Carregando lotes...</p>:!data.length?<EmptyState title="Nenhum lote" description="Registre lotes manualmente ou pelo recebimento de compras."/>:<DataTable headers={["Produto","Lote","Quantidade","Custo","Validade","Situação","Ações"]}>{data.map(item=><tr key={item.id}><td className="px-4 py-3 font-medium">{item.product_name}</td><td className="px-4 py-3">{item.lot_code||`#${item.id}`}</td><td className="px-4 py-3">{item.current_quantity}</td><td className="px-4 py-3">{formatCurrency(item.unit_cost)}</td><td className="px-4 py-3">{item.expiration_date?new Date(item.expiration_date+"T12:00:00").toLocaleDateString("pt-BR"):"Sem validade"}</td><td className="px-4 py-3"><Badge label={item.expiry_state}/></td><td className="px-4 py-3"><Button variant="secondary" disabled={item.current_quantity<=0} onClick={()=>{setLossLot(item);setLoss(current=>({...current,quantity:Math.min(1,item.current_quantity)}));}}><AlertTriangle size={15} className="mr-1"/>Registrar perda</Button></td></tr>)}</DataTable>}</Card>
  {lotOpen&&<Modal title="Novo lote" onClose={()=>setLotOpen(false)}><form className="grid gap-4 md:grid-cols-2" onSubmit={create}><label className="text-sm">Produto<select required className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.product_id} onChange={e=>setForm({...form,product_id:Number(e.target.value)})}><option value={0}>Selecione</option>{products?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm">Fornecedor<select className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:Number(e.target.value)})}><option value={0}>Opcional</option>{suppliers?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm">Código do lote<input className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.lot_code} onChange={e=>setForm({...form,lot_code:e.target.value})}/></label><label className="text-sm">Validade<input type="date" className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.expiration_date} onChange={e=>setForm({...form,expiration_date:e.target.value})}/></label><label className="text-sm">Quantidade<input type="number" min="0.001" step="0.001" className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label><label className="text-sm">Custo unitário<input type="number" min="0" step="0.01" className="mt-1 w-full rounded-xl border-stroke bg-white" value={form.unit_cost} onChange={e=>setForm({...form,unit_cost:Number(e.target.value)})}/></label><label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" checked={form.add_to_stock} onChange={e=>setForm({...form,add_to_stock:e.target.checked})}/>Somar quantidade ao estoque atual</label><Button className="md:col-span-2" disabled={!form.product_id}>Salvar lote</Button></form></Modal>}
  {lossLot&&<Modal title={`Perda · ${lossLot.product_name}`} onClose={()=>setLossLot(null)}><div className="space-y-4"><label className="block text-sm">Quantidade<input type="number" min="0.001" max={lossLot.current_quantity} step="0.001" className="mt-1 w-full rounded-xl border-stroke bg-white" value={loss.quantity} onChange={e=>setLoss({...loss,quantity:Number(e.target.value)})}/></label><label className="block text-sm">Motivo<select className="mt-1 w-full rounded-xl border-stroke bg-white" value={loss.reason} onChange={e=>setLoss({...loss,reason:e.target.value})}>{["VENCIDO","DANIFICADO","QUEBRA","CONSUMO_INTERNO","FURTO","OUTRO"].map(item=><option key={item}>{item}</option>)}</select></label><label className="block text-sm">Observação<textarea className="mt-1 w-full rounded-xl border-stroke bg-white" value={loss.notes} onChange={e=>setLoss({...loss,notes:e.target.value})}/></label><Button className="w-full" onClick={()=>void createLoss()}>Confirmar baixa</Button></div></Modal>}</div>;
}
